algorithm: ppo
indicator_stats_path: autotest_models/model_007_indicator_stats.json
model_id: model_007
model_path: autotest_models/model_007_ppo.zip
parameters:
  algorithm: ppo
  batch_size: 32
  clip_range: 0.2
  ent_coef: 0.0
  gamma: 0.995
  learning_rate: 0.0001
  model_id: model_007
  n_steps: 4096
  name: ppo_model_007
  net_arch:
  - - 512
    - 256
  - - 512
    - 256
  tech_indicators: &id001
  - adxr
  - close_50_sma
  - willr
  - close_60_sma
  - cci_14
  tickers: &id002
  - AAPL
  - GOOGL
  - AMZN
  - MSFT
  - NVDA
  timesteps: 1500000
tech_indicators: *id001
tickers: *id002
training_date: '2026-01-20T16:15:52.927833'
vecnormalize_path: autotest_models/model_007_ppo_vecnormalize.pkl
