algorithm: ppo
indicator_stats_path: autotest_models/model_006_indicator_stats.json
model_id: model_006
model_path: autotest_models/model_006_ppo.zip
parameters:
  algorithm: ppo
  batch_size: 128
  clip_range: 0.1
  ent_coef: 0.0
  gamma: 0.99
  learning_rate: 0.0003
  model_id: model_006
  n_steps: 1024
  name: ppo_model_006
  net_arch:
  - - 256
    - 256
    - 128
  - - 256
    - 256
    - 128
  tech_indicators: &id001
  - close_50_sma
  - rsi_14
  - close_60_sma
  - willr
  - atr
  tickers: &id002
  - AAPL
  - MSFT
  - GOOGL
  timesteps: 1500000
tech_indicators: *id001
tickers: *id002
training_date: '2026-01-20T15:56:34.969242'
vecnormalize_path: autotest_models/model_006_ppo_vecnormalize.pkl
