algorithm: ppo
indicator_stats_path: autotest_models/model_005_indicator_stats.json
model_id: model_005
model_path: autotest_models/model_005_ppo.zip
parameters:
  algorithm: ppo
  batch_size: 128
  clip_range: 0.3
  ent_coef: 0.05
  gamma: 0.95
  learning_rate: 0.0005
  model_id: model_005
  n_steps: 1024
  name: ppo_model_005
  net_arch:
  - - 256
    - 128
  - - 256
    - 128
  tech_indicators: &id001
  - willr
  - boll_lb
  - close_50_sma
  tickers: &id002
  - SPY
  - QQQ
  - DIA
  timesteps: 1500000
tech_indicators: *id001
tickers: *id002
training_date: '2026-01-20T15:45:13.564834'
vecnormalize_path: autotest_models/model_005_ppo_vecnormalize.pkl
