algorithm: ppo
indicator_stats_path: autotest_models/model_004_indicator_stats.json
model_id: model_004
model_path: autotest_models/model_004_ppo.zip
parameters:
  algorithm: ppo
  batch_size: 32
  clip_range: 0.2
  ent_coef: 0.0
  gamma: 0.99
  learning_rate: 0.0005
  model_id: model_004
  n_steps: 4096
  name: ppo_model_004
  net_arch:
  - - 256
    - 256
    - 128
  - - 256
    - 256
    - 128
  tech_indicators: &id001
  - dx_14
  - boll_ub
  - dx_30
  - close_20_sma
  - willr
  tickers: &id002
  - MSFT
  - AMZN
  - META
  timesteps: 1500000
tech_indicators: *id001
tickers: *id002
training_date: '2026-01-20T15:35:43.318691'
vecnormalize_path: autotest_models/model_004_ppo_vecnormalize.pkl
