algorithm: ppo
indicator_stats_path: autotest_models/model_001_indicator_stats.json
model_id: model_001
model_path: autotest_models/model_001_ppo.zip
parameters:
  algorithm: ppo
  batch_size: 128
  clip_range: 0.3
  ent_coef: 0.01
  gamma: 0.95
  learning_rate: 0.001
  model_id: model_001
  n_steps: 2048
  name: ppo_model_001
  net_arch:
  - - 128
    - 64
  - - 128
    - 64
  tech_indicators: &id001
  - boll_lb
  - dx_14
  - dx_30
  tickers: &id002
  - SPY
  - QQQ
  - DIA
  timesteps: 1500000
tech_indicators: *id001
tickers: *id002
training_date: '2026-01-20T14:55:05.316977'
vecnormalize_path: autotest_models/model_001_ppo_vecnormalize.pkl
