algorithm: ppo
indicator_stats_path: autotest_models/model_011_indicator_stats.json
model_id: model_011
model_path: autotest_models/model_011_ppo.zip
parameters:
  algorithm: ppo
  batch_size: 32
  clip_range: 0.2
  ent_coef: 0.0
  gamma: 0.995
  learning_rate: 0.0003
  model_id: model_011
  n_steps: 4096
  name: ppo_model_011
  net_arch:
  - - 128
    - 64
  - - 128
    - 64
  tech_indicators: &id001
  - close_50_sma
  - dx_30
  - cci_14
  tickers: &id002
  - AAPL
  - MSFT
  - GOOGL
  timesteps: 1500000
tech_indicators: *id001
tickers: *id002
training_date: '2026-01-20T17:04:33.546798'
vecnormalize_path: autotest_models/model_011_ppo_vecnormalize.pkl
