algorithm: ppo
indicator_stats_path: autotest_models/model_009_indicator_stats.json
model_id: model_009
model_path: autotest_models/model_009_ppo.zip
parameters:
  algorithm: ppo
  batch_size: 64
  clip_range: 0.3
  ent_coef: 0.0
  gamma: 0.95
  learning_rate: 0.0003
  model_id: model_009
  n_steps: 4096
  name: ppo_model_009
  net_arch:
  - - 512
    - 256
  - - 512
    - 256
  tech_indicators: &id001
  - adxr
  - close_60_sma
  - close_50_sma
  tickers: &id002
  - SPY
  - QQQ
  - DIA
  timesteps: 1500000
tech_indicators: *id001
tickers: *id002
training_date: '2026-01-20T16:38:33.017626'
vecnormalize_path: autotest_models/model_009_ppo_vecnormalize.pkl
