parameter_sets:
- algorithm: ppo
  batch_size: 128
  clip_range: 0.3
  ent_coef: 0.01
  gamma: 0.95
  learning_rate: 0.001
  model_id: model_001
  n_steps: 2048
  name: ppo_model_001
  net_arch: &id001
  - - 128
    - 64
  - - 128
    - 64
  tech_indicators:
  - boll_lb
  - dx_14
  - dx_30
  tickers: &id003
  - SPY
  - QQQ
  - DIA
  timesteps: 1500000
- algorithm: ppo
  batch_size: 128
  clip_range: 0.3
  ent_coef: 0.05
  gamma: 0.99
  learning_rate: 0.0003
  model_id: model_002
  n_steps: 4096
  name: ppo_model_002
  net_arch: &id002
  - - 256
    - 128
  - - 256
    - 128
  tech_indicators:
  - willr
  - dx_14
  - close_30_sma
  tickers: &id008
  - XLF
  - XLK
  - XLE
  - XLV
  timesteps: 1500000
- algorithm: ppo
  batch_size: 64
  clip_range: 0.3
  ent_coef: 0.0
  gamma: 0.95
  learning_rate: 0.0003
  model_id: model_003
  n_steps: 1024
  name: ppo_model_003
  net_arch: *id001
  tech_indicators:
  - dx_14
  - close_50_sma
  - cci_14
  - close_20_sma
  tickers: &id005
  - AAPL
  - MSFT
  - GOOGL
  timesteps: 1500000
- algorithm: ppo
  batch_size: 32
  clip_range: 0.2
  ent_coef: 0.0
  gamma: 0.99
  learning_rate: 0.0005
  model_id: model_004
  n_steps: 4096
  name: ppo_model_004
  net_arch: &id004
  - - 256
    - 256
    - 128
  - - 256
    - 256
    - 128
  tech_indicators:
  - dx_14
  - boll_ub
  - dx_30
  - close_20_sma
  - willr
  tickers:
  - MSFT
  - AMZN
  - META
  timesteps: 1500000
- algorithm: ppo
  batch_size: 128
  clip_range: 0.3
  ent_coef: 0.05
  gamma: 0.95
  learning_rate: 0.0005
  model_id: model_005
  n_steps: 1024
  name: ppo_model_005
  net_arch: *id002
  tech_indicators:
  - willr
  - boll_lb
  - close_50_sma
  tickers: *id003
  timesteps: 1500000
- algorithm: ppo
  batch_size: 128
  clip_range: 0.1
  ent_coef: 0.0
  gamma: 0.99
  learning_rate: 0.0003
  model_id: model_006
  n_steps: 1024
  name: ppo_model_006
  net_arch: *id004
  tech_indicators:
  - close_50_sma
  - rsi_14
  - close_60_sma
  - willr
  - atr
  tickers: *id005
  timesteps: 1500000
- algorithm: ppo
  batch_size: 32
  clip_range: 0.2
  ent_coef: 0.0
  gamma: 0.995
  learning_rate: 0.0001
  model_id: model_007
  n_steps: 4096
  name: ppo_model_007
  net_arch: &id006
  - - 512
    - 256
  - - 512
    - 256
  tech_indicators:
  - adxr
  - close_50_sma
  - willr
  - close_60_sma
  - cci_14
  tickers: &id007
  - AAPL
  - GOOGL
  - AMZN
  - MSFT
  - NVDA
  timesteps: 1500000
- algorithm: ppo
  batch_size: 128
  clip_range: 0.1
  ent_coef: 0.05
  gamma: 0.99
  learning_rate: 0.0005
  model_id: model_008
  n_steps: 4096
  name: ppo_model_008
  net_arch: *id001
  tech_indicators:
  - dx_30
  - close_20_sma
  - close_30_sma
  - rsi_14
  tickers: *id005
  timesteps: 1500000
- algorithm: ppo
  batch_size: 64
  clip_range: 0.3
  ent_coef: 0.0
  gamma: 0.95
  learning_rate: 0.0003
  model_id: model_009
  n_steps: 4096
  name: ppo_model_009
  net_arch: *id006
  tech_indicators:
  - adxr
  - close_60_sma
  - close_50_sma
  tickers: *id003
  timesteps: 1500000
- algorithm: ppo
  batch_size: 128
  clip_range: 0.1
  ent_coef: 0.01
  gamma: 0.995
  learning_rate: 0.002
  model_id: model_010
  n_steps: 1024
  name: ppo_model_010
  net_arch: *id006
  tech_indicators:
  - cci_30
  - adxr
  - rsi_14
  tickers: *id007
  timesteps: 1500000
- algorithm: ppo
  batch_size: 32
  clip_range: 0.2
  ent_coef: 0.0
  gamma: 0.995
  learning_rate: 0.0003
  model_id: model_011
  n_steps: 4096
  name: ppo_model_011
  net_arch: *id001
  tech_indicators:
  - close_50_sma
  - dx_30
  - cci_14
  tickers: *id005
  timesteps: 1500000
- algorithm: ppo
  batch_size: 32
  clip_range: 0.3
  ent_coef: 0.01
  gamma: 0.95
  learning_rate: 0.0003
  model_id: model_012
  n_steps: 4096
  name: ppo_model_012
  net_arch: *id006
  tech_indicators:
  - rsi_14
  - boll_ub
  - cci_30
  - rsi_30
  tickers:
  - TSLA
  - NVDA
  - AMD
  - INTC
  timesteps: 1500000
- algorithm: ppo
  batch_size: 64
  clip_range: 0.1
  ent_coef: 0.01
  gamma: 0.995
  learning_rate: 0.0003
  model_id: model_013
  n_steps: 2048
  name: ppo_model_013
  net_arch: *id002
  tech_indicators:
  - adx
  - dx_30
  - close_20_sma
  - cci_30
  tickers:
  - JPM
  - BAC
  - WFC
  - GS
  timesteps: 1500000
- algorithm: ppo
  batch_size: 64
  clip_range: 0.1
  ent_coef: 0.0
  gamma: 0.995
  learning_rate: 0.0005
  model_id: model_014
  n_steps: 4096
  name: ppo_model_014
  net_arch: *id006
  tech_indicators:
  - adx
  - close_20_sma
  - boll_ub
  - close_50_sma
  tickers: *id008
  timesteps: 1500000
- algorithm: ppo
  batch_size: 32
  clip_range: 0.2
  ent_coef: 0.0
  gamma: 0.995
  learning_rate: 0.002
  model_id: model_015
  n_steps: 4096
  name: ppo_model_015
  net_arch: *id001
  tech_indicators:
  - boll_lb
  - cci_14
  - rsi_30
  - dx_30
  - atr
  tickers: *id008
  timesteps: 1500000
