parameter_sets:
- algorithm: ppo
  batch_size: 32
  clip_range: 0.2
  ent_coef: 0.01
  gamma: 0.99
  initial_capital: 50000
  learning_rate: 0.0005
  model_id: model_001
  n_steps: 4096
  name: ppo_model_001
  reward_scaling: 1e-5
  tickers: &id001
  - SPY
  - QQQ
  - DIA
  timesteps: 1500000
- algorithm: ppo
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.0
  gamma: 0.995
  initial_capital: 50000
  learning_rate: 0.0005
  model_id: model_002
  n_steps: 2048
  name: ppo_model_002
  reward_scaling: 1e-5
  tickers:
  - TSLA
  - NVDA
  - AMD
  - INTC
  timesteps: 1500000
- algorithm: ppo
  batch_size: 64
  clip_range: 0.1
  ent_coef: 0.05
  gamma: 0.99
  initial_capital: 100000
  learning_rate: 0.002
  model_id: model_003
  n_steps: 1024
  name: ppo_model_003
  reward_scaling: 1e-5
  tickers: &id002
  - XLF
  - XLK
  - XLE
  - XLV
  timesteps: 1500000
- algorithm: ppo
  batch_size: 128
  clip_range: 0.3
  ent_coef: 0.05
  gamma: 0.95
  initial_capital: 50000
  learning_rate: 0.001
  model_id: model_004
  n_steps: 1024
  name: ppo_model_004
  reward_scaling: 1e-5
  tickers:
  - AAPL
  - NVDA
  - TSLA
  timesteps: 1500000
- algorithm: ppo
  batch_size: 128
  clip_range: 0.3
  ent_coef: 0.0
  gamma: 0.99
  initial_capital: 100000
  learning_rate: 0.0005
  model_id: model_005
  n_steps: 1024
  name: ppo_model_005
  reward_scaling: 1e-4
  tickers:
  - JPM
  - BAC
  - WFC
  - GS
  timesteps: 1500000
- algorithm: ppo
  batch_size: 128
  clip_range: 0.2
  ent_coef: 0.01
  gamma: 0.995
  initial_capital: 50000
  learning_rate: 0.0005
  model_id: model_006
  n_steps: 4096
  name: ppo_model_006
  reward_scaling: 1e-5
  tickers: *id001
  timesteps: 1500000
- algorithm: ppo
  batch_size: 32
  clip_range: 0.3
  ent_coef: 0.0
  gamma: 0.95
  initial_capital: 50000
  learning_rate: 0.0003
  model_id: model_007
  n_steps: 2048
  name: ppo_model_007
  reward_scaling: 1e-5
  tickers: *id002
  timesteps: 1500000
- algorithm: ppo
  batch_size: 32
  clip_range: 0.1
  ent_coef: 0.01
  gamma: 0.995
  initial_capital: 50000
  learning_rate: 0.001
  model_id: model_008
  n_steps: 2048
  name: ppo_model_008
  reward_scaling: 1e-5
  tickers:
  - AAPL
  - MSFT
  - GOOGL
  timesteps: 1500000
- algorithm: ppo
  batch_size: 64
  clip_range: 0.3
  ent_coef: 0.05
  gamma: 0.995
  initial_capital: 50000
  learning_rate: 0.002
  model_id: model_009
  n_steps: 2048
  name: ppo_model_009
  reward_scaling: 1e-5
  tickers:
  - AAPL
  - GOOGL
  - AMZN
  - MSFT
  - NVDA
  timesteps: 1500000
- algorithm: ppo
  batch_size: 64
  clip_range: 0.3
  ent_coef: 0.01
  gamma: 0.995
  initial_capital: 200000
  learning_rate: 0.001
  model_id: model_010
  n_steps: 4096
  name: ppo_model_010
  reward_scaling: 1e-3
  tickers: *id002
  timesteps: 1500000
- algorithm: ppo
  batch_size: 32
  clip_range: 0.3
  ent_coef: 0.01
  gamma: 0.99
  initial_capital: 200000
  learning_rate: 0.0001
  model_id: model_011
  n_steps: 1024
  name: ppo_model_011
  reward_scaling: 1e-4
  tickers: &id003
  - MSFT
  - AMZN
  - META
  timesteps: 1500000
- algorithm: ppo
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.01
  gamma: 0.95
  initial_capital: 100000
  learning_rate: 0.001
  model_id: model_012
  n_steps: 2048
  name: ppo_model_012
  reward_scaling: 1e-3
  tickers:
  - AAPL
  - MSFT
  - NVDA
  - GOOGL
  timesteps: 1500000
- algorithm: ppo
  batch_size: 32
  clip_range: 0.3
  ent_coef: 0.0
  gamma: 0.995
  initial_capital: 100000
  learning_rate: 0.0003
  model_id: model_013
  n_steps: 4096
  name: ppo_model_013
  reward_scaling: 1e-4
  tickers: *id003
  timesteps: 1500000
- algorithm: ppo
  batch_size: 128
  clip_range: 0.3
  ent_coef: 0.0
  gamma: 0.995
  initial_capital: 200000
  learning_rate: 0.001
  model_id: model_014
  n_steps: 4096
  name: ppo_model_014
  reward_scaling: 1e-5
  tickers: *id001
  timesteps: 1500000
- algorithm: ppo
  batch_size: 32
  clip_range: 0.3
  ent_coef: 0.01
  gamma: 0.95
  initial_capital: 200000
  learning_rate: 0.001
  model_id: model_015
  n_steps: 1024
  name: ppo_model_015
  reward_scaling: 1e-3
  tickers: *id003
  timesteps: 1500000
