parameter_sets:
- algorithm: ppo
  batch_size: 32
  clip_range: 0.2
  ent_coef: 0.0
  gamma: 0.99
  initial_capital: 200000
  learning_rate: 0.0003
  model_id: model_001
  n_steps: 4096
  name: ppo_model_001
  reward_scaling: 1.0e-05
  tech_indicators:
  - close_20_sma
  - atr
  - rsi_14
  - rsi_30
  - cci_30
  tickers: &id003
  - MSFT
  - AMZN
  - META
  timesteps: 1500000
- algorithm: ppo
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.0
  gamma: 0.95
  initial_capital: 100000
  learning_rate: 0.002
  model_id: model_002
  n_steps: 1024
  name: ppo_model_002
  reward_scaling: 0.001
  tech_indicators:
  - close_30_sma
  - boll_lb
  - dx_14
  tickers:
  - JPM
  - BAC
  - WFC
  - GS
  timesteps: 1500000
- algorithm: ppo
  batch_size: 64
  clip_range: 0.3
  ent_coef: 0.01
  gamma: 0.995
  initial_capital: 100000
  learning_rate: 0.002
  model_id: model_003
  n_steps: 2048
  name: ppo_model_003
  reward_scaling: 1.0e-05
  tech_indicators:
  - atr
  - boll_ub
  - dx_14
  - close_20_sma
  - adxr
  tickers: &id001
  - AAPL
  - MSFT
  - NVDA
  - GOOGL
  timesteps: 1500000
- algorithm: ppo
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.01
  gamma: 0.99
  initial_capital: 200000
  learning_rate: 0.0005
  model_id: model_004
  n_steps: 4096
  name: ppo_model_004
  reward_scaling: 1.0e-05
  tech_indicators:
  - close_20_sma
  - close_50_sma
  - atr
  - cci_30
  tickers:
  - AAPL
  - MSFT
  - GOOGL
  timesteps: 1500000
- algorithm: ppo
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.01
  gamma: 0.95
  initial_capital: 100000
  learning_rate: 0.0005
  model_id: model_005
  n_steps: 4096
  name: ppo_model_005
  reward_scaling: 0.0001
  tech_indicators:
  - rsi_14
  - close_20_sma
  - adxr
  - cci_30
  tickers: &id004
  - AAPL
  - NVDA
  - TSLA
  timesteps: 1500000
- algorithm: ppo
  batch_size: 64
  clip_range: 0.1
  ent_coef: 0.05
  gamma: 0.995
  initial_capital: 50000
  learning_rate: 0.0005
  model_id: model_006
  n_steps: 4096
  name: ppo_model_006
  reward_scaling: 1.0e-05
  tech_indicators:
  - boll_ub
  - dx_30
  - rsi_30
  tickers:
  - TSLA
  - NVDA
  - AMD
  - INTC
  timesteps: 1500000
- algorithm: ppo
  batch_size: 64
  clip_range: 0.1
  ent_coef: 0.05
  gamma: 0.995
  initial_capital: 200000
  learning_rate: 0.0005
  model_id: model_007
  n_steps: 4096
  name: ppo_model_007
  reward_scaling: 0.0001
  tech_indicators:
  - close_50_sma
  - atr
  - close_60_sma
  tickers: *id001
  timesteps: 1500000
- algorithm: ppo
  batch_size: 32
  clip_range: 0.3
  ent_coef: 0.0
  gamma: 0.95
  initial_capital: 100000
  learning_rate: 0.0003
  model_id: model_008
  n_steps: 1024
  name: ppo_model_008
  reward_scaling: 0.0001
  tech_indicators:
  - adxr
  - macd
  - boll_lb
  tickers: &id002
  - GOOGL
  - NVDA
  - AMD
  timesteps: 1500000
- algorithm: ppo
  batch_size: 128
  clip_range: 0.1
  ent_coef: 0.05
  gamma: 0.995
  initial_capital: 200000
  learning_rate: 0.001
  model_id: model_009
  n_steps: 1024
  name: ppo_model_009
  reward_scaling: 0.001
  tech_indicators:
  - rsi_14
  - dx_14
  - atr
  - close_50_sma
  - cci_30
  tickers: *id002
  timesteps: 1500000
- algorithm: ppo
  batch_size: 128
  clip_range: 0.1
  ent_coef: 0.05
  gamma: 0.995
  initial_capital: 100000
  learning_rate: 0.0005
  model_id: model_010
  n_steps: 2048
  name: ppo_model_010
  reward_scaling: 1.0e-05
  tech_indicators:
  - close_20_sma
  - adx
  - cci_14
  tickers: *id003
  timesteps: 1500000
- algorithm: ppo
  batch_size: 32
  clip_range: 0.2
  ent_coef: 0.0
  gamma: 0.995
  initial_capital: 100000
  learning_rate: 0.0005
  model_id: model_011
  n_steps: 2048
  name: ppo_model_011
  reward_scaling: 0.001
  tech_indicators:
  - boll_ub
  - dx_14
  - macd
  - rsi_14
  - adx
  tickers: *id003
  timesteps: 1500000
- algorithm: ppo
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.01
  gamma: 0.95
  initial_capital: 200000
  learning_rate: 0.001
  model_id: model_012
  n_steps: 4096
  name: ppo_model_012
  reward_scaling: 0.0001
  tech_indicators:
  - close_30_sma
  - atr
  - close_50_sma
  - dx_14
  tickers:
  - XLF
  - XLK
  - XLE
  - XLV
  timesteps: 1500000
- algorithm: ppo
  batch_size: 32
  clip_range: 0.1
  ent_coef: 0.05
  gamma: 0.95
  initial_capital: 100000
  learning_rate: 0.002
  model_id: model_013
  n_steps: 4096
  name: ppo_model_013
  reward_scaling: 0.001
  tech_indicators:
  - cci_30
  - macd
  - dx_14
  - adxr
  tickers: *id001
  timesteps: 1500000
- algorithm: ppo
  batch_size: 64
  clip_range: 0.3
  ent_coef: 0.0
  gamma: 0.99
  initial_capital: 50000
  learning_rate: 0.002
  model_id: model_014
  n_steps: 4096
  name: ppo_model_014
  reward_scaling: 0.001
  tech_indicators:
  - close_30_sma
  - rsi_30
  - dx_14
  - macd
  tickers: *id004
  timesteps: 1500000
- algorithm: ppo
  batch_size: 128
  clip_range: 0.3
  ent_coef: 0.05
  gamma: 0.95
  initial_capital: 50000
  learning_rate: 0.001
  model_id: model_015
  n_steps: 4096
  name: ppo_model_015
  reward_scaling: 1.0e-05
  tech_indicators:
  - atr
  - cci_30
  - boll_ub
  - adxr
  - willr
  tickers: *id004
  timesteps: 1500000
