failed: 15
results:
- error: No valid dates found in dataframe
  model_id: model_001
  model_path: null
  params:
    algorithm: ppo
    batch_size: 32
    clip_range: 0.1
    ent_coef: 0.05
    gamma: 0.995
    initial_capital: 100000
    learning_rate: 0.0003
    model_id: model_001
    n_steps: 1024
    name: ppo_model_001
    reward_scaling: 1e-5
    tickers: &id001
    - GOOGL
    - NVDA
    - AMD
    timesteps: 1500000
  success: false
  traceback: "Traceback (most recent call last):\n  File \"/home/salt/CodingProjects/RLFI/src/autotest/automated_trainer.py\"\
    , line 107, in train_model\n    train_df, val_df, test_df = data_loader.split_data(\n\
    \  File \"/home/salt/CodingProjects/RLFI/src/data/data_loader.py\", line 78, in\
    \ split_data\n    raise ValueError(\"No valid dates found in dataframe\")\nValueError:\
    \ No valid dates found in dataframe\n"
  training_time: 0.46179
- error: No valid dates found in dataframe
  model_id: model_002
  model_path: null
  params:
    algorithm: ppo
    batch_size: 64
    clip_range: 0.2
    ent_coef: 0.0
    gamma: 0.995
    initial_capital: 100000
    learning_rate: 0.0005
    model_id: model_002
    n_steps: 2048
    name: ppo_model_002
    reward_scaling: 1e-4
    tickers: &id003
    - JPM
    - BAC
    - WFC
    - GS
    timesteps: 1500000
  success: false
  traceback: "Traceback (most recent call last):\n  File \"/home/salt/CodingProjects/RLFI/src/autotest/automated_trainer.py\"\
    , line 107, in train_model\n    train_df, val_df, test_df = data_loader.split_data(\n\
    \  File \"/home/salt/CodingProjects/RLFI/src/data/data_loader.py\", line 78, in\
    \ split_data\n    raise ValueError(\"No valid dates found in dataframe\")\nValueError:\
    \ No valid dates found in dataframe\n"
  training_time: 0.610718
- error: No valid dates found in dataframe
  model_id: model_003
  model_path: null
  params:
    algorithm: ppo
    batch_size: 128
    clip_range: 0.3
    ent_coef: 0.0
    gamma: 0.95
    initial_capital: 100000
    learning_rate: 0.0005
    model_id: model_003
    n_steps: 1024
    name: ppo_model_003
    reward_scaling: 1e-5
    tickers:
    - SPY
    - QQQ
    - DIA
    timesteps: 1500000
  success: false
  traceback: "Traceback (most recent call last):\n  File \"/home/salt/CodingProjects/RLFI/src/autotest/automated_trainer.py\"\
    , line 107, in train_model\n    train_df, val_df, test_df = data_loader.split_data(\n\
    \  File \"/home/salt/CodingProjects/RLFI/src/data/data_loader.py\", line 78, in\
    \ split_data\n    raise ValueError(\"No valid dates found in dataframe\")\nValueError:\
    \ No valid dates found in dataframe\n"
  training_time: 0.459527
- error: No valid dates found in dataframe
  model_id: model_004
  model_path: null
  params:
    algorithm: ppo
    batch_size: 128
    clip_range: 0.3
    ent_coef: 0.05
    gamma: 0.95
    initial_capital: 100000
    learning_rate: 0.0003
    model_id: model_004
    n_steps: 2048
    name: ppo_model_004
    reward_scaling: 1e-5
    tickers: &id002
    - TSLA
    - NVDA
    - AMD
    - INTC
    timesteps: 1500000
  success: false
  traceback: "Traceback (most recent call last):\n  File \"/home/salt/CodingProjects/RLFI/src/autotest/automated_trainer.py\"\
    , line 107, in train_model\n    train_df, val_df, test_df = data_loader.split_data(\n\
    \  File \"/home/salt/CodingProjects/RLFI/src/data/data_loader.py\", line 78, in\
    \ split_data\n    raise ValueError(\"No valid dates found in dataframe\")\nValueError:\
    \ No valid dates found in dataframe\n"
  training_time: 0.455906
- error: No valid dates found in dataframe
  model_id: model_005
  model_path: null
  params:
    algorithm: ppo
    batch_size: 128
    clip_range: 0.3
    ent_coef: 0.0
    gamma: 0.95
    initial_capital: 50000
    learning_rate: 0.0003
    model_id: model_005
    n_steps: 4096
    name: ppo_model_005
    reward_scaling: 1e-3
    tickers: &id004
    - XLF
    - XLK
    - XLE
    - XLV
    timesteps: 1500000
  success: false
  traceback: "Traceback (most recent call last):\n  File \"/home/salt/CodingProjects/RLFI/src/autotest/automated_trainer.py\"\
    , line 107, in train_model\n    train_df, val_df, test_df = data_loader.split_data(\n\
    \  File \"/home/salt/CodingProjects/RLFI/src/data/data_loader.py\", line 78, in\
    \ split_data\n    raise ValueError(\"No valid dates found in dataframe\")\nValueError:\
    \ No valid dates found in dataframe\n"
  training_time: 0.460837
- error: No valid dates found in dataframe
  model_id: model_006
  model_path: null
  params:
    algorithm: ppo
    batch_size: 32
    clip_range: 0.3
    ent_coef: 0.01
    gamma: 0.995
    initial_capital: 50000
    learning_rate: 0.0001
    model_id: model_006
    n_steps: 4096
    name: ppo_model_006
    reward_scaling: 1e-3
    tickers: *id001
    timesteps: 1500000
  success: false
  traceback: "Traceback (most recent call last):\n  File \"/home/salt/CodingProjects/RLFI/src/autotest/automated_trainer.py\"\
    , line 107, in train_model\n    train_df, val_df, test_df = data_loader.split_data(\n\
    \  File \"/home/salt/CodingProjects/RLFI/src/data/data_loader.py\", line 78, in\
    \ split_data\n    raise ValueError(\"No valid dates found in dataframe\")\nValueError:\
    \ No valid dates found in dataframe\n"
  training_time: 0.460066
- error: No valid dates found in dataframe
  model_id: model_007
  model_path: null
  params:
    algorithm: ppo
    batch_size: 128
    clip_range: 0.3
    ent_coef: 0.0
    gamma: 0.99
    initial_capital: 200000
    learning_rate: 0.002
    model_id: model_007
    n_steps: 2048
    name: ppo_model_007
    reward_scaling: 1e-4
    tickers: &id005
    - AAPL
    - MSFT
    - GOOGL
    timesteps: 1500000
  success: false
  traceback: "Traceback (most recent call last):\n  File \"/home/salt/CodingProjects/RLFI/src/autotest/automated_trainer.py\"\
    , line 107, in train_model\n    train_df, val_df, test_df = data_loader.split_data(\n\
    \  File \"/home/salt/CodingProjects/RLFI/src/data/data_loader.py\", line 78, in\
    \ split_data\n    raise ValueError(\"No valid dates found in dataframe\")\nValueError:\
    \ No valid dates found in dataframe\n"
  training_time: 0.605204
- error: No valid dates found in dataframe
  model_id: model_008
  model_path: null
  params:
    algorithm: ppo
    batch_size: 128
    clip_range: 0.1
    ent_coef: 0.01
    gamma: 0.95
    initial_capital: 100000
    learning_rate: 0.001
    model_id: model_008
    n_steps: 2048
    name: ppo_model_008
    reward_scaling: 1e-4
    tickers: *id001
    timesteps: 1500000
  success: false
  traceback: "Traceback (most recent call last):\n  File \"/home/salt/CodingProjects/RLFI/src/autotest/automated_trainer.py\"\
    , line 107, in train_model\n    train_df, val_df, test_df = data_loader.split_data(\n\
    \  File \"/home/salt/CodingProjects/RLFI/src/data/data_loader.py\", line 78, in\
    \ split_data\n    raise ValueError(\"No valid dates found in dataframe\")\nValueError:\
    \ No valid dates found in dataframe\n"
  training_time: 0.455496
- error: No valid dates found in dataframe
  model_id: model_009
  model_path: null
  params:
    algorithm: ppo
    batch_size: 128
    clip_range: 0.3
    ent_coef: 0.05
    gamma: 0.995
    initial_capital: 200000
    learning_rate: 0.001
    model_id: model_009
    n_steps: 1024
    name: ppo_model_009
    reward_scaling: 1e-5
    tickers: *id002
    timesteps: 1500000
  success: false
  traceback: "Traceback (most recent call last):\n  File \"/home/salt/CodingProjects/RLFI/src/autotest/automated_trainer.py\"\
    , line 107, in train_model\n    train_df, val_df, test_df = data_loader.split_data(\n\
    \  File \"/home/salt/CodingProjects/RLFI/src/data/data_loader.py\", line 78, in\
    \ split_data\n    raise ValueError(\"No valid dates found in dataframe\")\nValueError:\
    \ No valid dates found in dataframe\n"
  training_time: 0.6019
- error: No valid dates found in dataframe
  model_id: model_010
  model_path: null
  params:
    algorithm: ppo
    batch_size: 128
    clip_range: 0.2
    ent_coef: 0.05
    gamma: 0.95
    initial_capital: 200000
    learning_rate: 0.0003
    model_id: model_010
    n_steps: 2048
    name: ppo_model_010
    reward_scaling: 1e-3
    tickers: *id003
    timesteps: 1500000
  success: false
  traceback: "Traceback (most recent call last):\n  File \"/home/salt/CodingProjects/RLFI/src/autotest/automated_trainer.py\"\
    , line 107, in train_model\n    train_df, val_df, test_df = data_loader.split_data(\n\
    \  File \"/home/salt/CodingProjects/RLFI/src/data/data_loader.py\", line 78, in\
    \ split_data\n    raise ValueError(\"No valid dates found in dataframe\")\nValueError:\
    \ No valid dates found in dataframe\n"
  training_time: 0.453993
- error: No valid dates found in dataframe
  model_id: model_011
  model_path: null
  params:
    algorithm: ppo
    batch_size: 128
    clip_range: 0.1
    ent_coef: 0.05
    gamma: 0.995
    initial_capital: 50000
    learning_rate: 0.002
    model_id: model_011
    n_steps: 1024
    name: ppo_model_011
    reward_scaling: 1e-3
    tickers:
    - AAPL
    - NVDA
    - TSLA
    timesteps: 1500000
  success: false
  traceback: "Traceback (most recent call last):\n  File \"/home/salt/CodingProjects/RLFI/src/autotest/automated_trainer.py\"\
    , line 107, in train_model\n    train_df, val_df, test_df = data_loader.split_data(\n\
    \  File \"/home/salt/CodingProjects/RLFI/src/data/data_loader.py\", line 78, in\
    \ split_data\n    raise ValueError(\"No valid dates found in dataframe\")\nValueError:\
    \ No valid dates found in dataframe\n"
  training_time: 0.601673
- error: No valid dates found in dataframe
  model_id: model_012
  model_path: null
  params:
    algorithm: ppo
    batch_size: 128
    clip_range: 0.2
    ent_coef: 0.0
    gamma: 0.995
    initial_capital: 200000
    learning_rate: 0.0001
    model_id: model_012
    n_steps: 4096
    name: ppo_model_012
    reward_scaling: 1e-4
    tickers: *id003
    timesteps: 1500000
  success: false
  traceback: "Traceback (most recent call last):\n  File \"/home/salt/CodingProjects/RLFI/src/autotest/automated_trainer.py\"\
    , line 107, in train_model\n    train_df, val_df, test_df = data_loader.split_data(\n\
    \  File \"/home/salt/CodingProjects/RLFI/src/data/data_loader.py\", line 78, in\
    \ split_data\n    raise ValueError(\"No valid dates found in dataframe\")\nValueError:\
    \ No valid dates found in dataframe\n"
  training_time: 0.603194
- error: No valid dates found in dataframe
  model_id: model_013
  model_path: null
  params:
    algorithm: ppo
    batch_size: 64
    clip_range: 0.1
    ent_coef: 0.0
    gamma: 0.99
    initial_capital: 100000
    learning_rate: 0.002
    model_id: model_013
    n_steps: 4096
    name: ppo_model_013
    reward_scaling: 1e-5
    tickers: *id001
    timesteps: 1500000
  success: false
  traceback: "Traceback (most recent call last):\n  File \"/home/salt/CodingProjects/RLFI/src/autotest/automated_trainer.py\"\
    , line 107, in train_model\n    train_df, val_df, test_df = data_loader.split_data(\n\
    \  File \"/home/salt/CodingProjects/RLFI/src/data/data_loader.py\", line 78, in\
    \ split_data\n    raise ValueError(\"No valid dates found in dataframe\")\nValueError:\
    \ No valid dates found in dataframe\n"
  training_time: 0.455303
- error: No valid dates found in dataframe
  model_id: model_014
  model_path: null
  params:
    algorithm: ppo
    batch_size: 64
    clip_range: 0.3
    ent_coef: 0.05
    gamma: 0.99
    initial_capital: 100000
    learning_rate: 0.0005
    model_id: model_014
    n_steps: 1024
    name: ppo_model_014
    reward_scaling: 1e-4
    tickers: *id004
    timesteps: 1500000
  success: false
  traceback: "Traceback (most recent call last):\n  File \"/home/salt/CodingProjects/RLFI/src/autotest/automated_trainer.py\"\
    , line 107, in train_model\n    train_df, val_df, test_df = data_loader.split_data(\n\
    \  File \"/home/salt/CodingProjects/RLFI/src/data/data_loader.py\", line 78, in\
    \ split_data\n    raise ValueError(\"No valid dates found in dataframe\")\nValueError:\
    \ No valid dates found in dataframe\n"
  training_time: 0.453237
- error: No valid dates found in dataframe
  model_id: model_015
  model_path: null
  params:
    algorithm: ppo
    batch_size: 128
    clip_range: 0.1
    ent_coef: 0.05
    gamma: 0.99
    initial_capital: 50000
    learning_rate: 0.0001
    model_id: model_015
    n_steps: 1024
    name: ppo_model_015
    reward_scaling: 1e-4
    tickers: *id005
    timesteps: 1500000
  success: false
  traceback: "Traceback (most recent call last):\n  File \"/home/salt/CodingProjects/RLFI/src/autotest/automated_trainer.py\"\
    , line 107, in train_model\n    train_df, val_df, test_df = data_loader.split_data(\n\
    \  File \"/home/salt/CodingProjects/RLFI/src/data/data_loader.py\", line 78, in\
    \ split_data\n    raise ValueError(\"No valid dates found in dataframe\")\nValueError:\
    \ No valid dates found in dataframe\n"
  training_time: 0.455164
successful: 0
total_models: 15
